# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r
# This runs current, and dev release of r on linux, but only current
# release of r on osx. This decision was because the packages that travis tried
# to download while testing out the osx build with dev version of r were not
# available at the url. The erroring of this build had nothing to do with the 
# SSMSE R package.

language: r
jobs:
  include:
  - r: oldrel
    os: linux
  - r: release
    os: linux
  - r: devel
    os: linux
sudo: required
cache: packages

services:
  - xvfb
  
script: 
  - |
    R CMD build .
    travis_wait 40 R CMD check SSMSE*tar.gz

notifications:
  email:
    recipients:
      - kathryn.doering@noaa.gov
      - nathan.vaughan@noaa.gov
    on_success: change
    on_failure: always

r_packages:
  - devtools
  - covr

warnings_are_errors: false

after_success:
  - Rscript -e 'library(covr); codecov()'
