# Run r cmd check
name: call-calc_coverage
on:
  push:
    paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - '**.MD'
      - '.gitignore'
  pull_request:
      paths-ignore:
      - '.github/**'
      - 'docs/**'
      - '**.md'
      - '**.MD'
      - '.gitignore'
jobs:
  call-workflow:
    uses: nmfs-fish-tools/ghactions4r/.github/workflows/calc-coverage.yml@main
