# Render readme, based on 
# https://raw.githubusercontent.com/r-lib/actions/master/.github/workflows/render-readme.yaml
name: Render README
on:
  workflow_dispatch:
  push:
    paths:
      - 'README.Rmd'
      - 'R/**'
jobs:
  render:
    name: Render README
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
        with:
          use-public-rspm: true
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown, remotes, and the local package
        run: |
          install.packages("devtools")
          devtools::install_local(".")
          devtools::install_cran("rmarkdown")
        shell: Rscript {0}
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
        
      - name: replace the data for bookdown
        run: |
          mv run_SSMSE-ex/results/SSMSE_scalar.csv inst/bookdown/data/SSMSE_scalar.csv
          mv run_SSMSE-ex/results/SSMSE_ts.csv inst/bookdown/data/SSMSE_ts.csv
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md -m 'docs: Re-build README.Rmd' || echo "No changes to commit"
          git add inst/bookdown/data/SSMSE_scalar.csv || echo "no changes to add for SSMSE_scalar.csv"
          git add inst/bookdown/data/SSMSE_ts.csv || echo "no changes to add for SSMSE_ts.csv"
          git commit -m 'bookdown: replace data' || echo "no bookdown data changes to commit"
          git push origin || echo "No changes to commit"